Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "flo-dolcS" do |server|
    server.vm.hostname = "flo-dolcS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.name = "flo-dolcS"
      v.memory = 1024
      v.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/setup.sh"
  end
end
