server {
    listen 8080;
    root www;
    index index.html index.htm;
    autoindex on;
    access_log logs/access.log;
    error_log logs/error.log;
    client_max_body_size 1000000;
    client_body_timeout 10s;
    client_header_timeout 10s;
    send_timeout 10s;
    error_page 400 /400.html;
    error_page 403 /403.html;
    error_page 404 /404.html;
    error_page 405 /405.html;
    error_page 500 /500.html;
    error_page 502 /502.html;
    error_page 503 /503.html;
    error_page 504 /504.html;
    location / {
        allowed_methods GET POST DELETE;
    }
    location /upload {
        root uploads;
        allowed_methods POST;
    }
    location /cgi-bin/ {
        root www/cgi-bin;
        cgi_pass /usr/bin/python3;
        allowed_methods GET POST;
    }
}

