server {
	server_name server1.local;
	listen 8080;
	root /var/www;
	autoindex on;
	host localhost;
	cgi_extension .py .php .pl;
	allow GET POST DELETE;
	client_max_body_size 50000000;

	error_page 404 /errors/404.html;
	error_page 500 /errors/500.html;

	location / {
		upload_dir /var/www/uploads/file;
	}

	location /json {
		upload_dir /var/www/uploads/json;
	}

	location /raw {
		upload_dir /var/www/uploads/raw;
	}
}

server {
	server_name server2.local;
	listen 8081;
	root /var/www;
	autoindex on;
	host localhost;
	cgi_extension .py .php .pl;
	allow GET POST DELETE;
	client_max_body_size 25000000;

	error_page 404 /errors/404.html;
	error_page 500 /errors/500.html;

	location / {
		upload_dir /var/www/uploads/file;
	}

	location /test {
		root /var/www/test;
		autoindex on;
	}
}

server {
	server_name server3.local;
	listen 8082;
	root /var/www;
	autoindex off;
	host localhost;
	cgi_extension .py;
	allow GET;
	client_max_body_size 10000000;

	error_page 404 /errors/404.html;
	error_page 500 /errors/500.html;

	location / {
		upload_dir /var/www/uploads/file;
		index index.html;
	}
}
