"""Messages exchanged between model, views and controllers.

Everything here is plain data with primitive fields, so that it can be
serialized (e.g. to JSON over a WebSocket) without changes.
"""

from pacman.protocol.commands import (
    Back,
    Backspace,
    Command,
    Confirm,
    MoveSelection,
    Quit,
    SetDirection,
    ToggleCheatMode,
    TypeCharacter,
    UseCheat,
)
from pacman.protocol.enums import (
    Cheat,
    Direction,
    FoodType,
    GhostState,
    Screen,
)
from pacman.protocol.events import (
    CheatsChanged,
    Event,
    FoodCollected,
    FoodSpawned,
    GameOver,
    GameWon,
    GhostMoved,
    GhostStateChanged,
    HighscoresChanged,
    LevelCompleted,
    LevelStarted,
    LivesChanged,
    MazeGenerated,
    MenuChanged,
    NameEntryChanged,
    PacmanCaught,
    PacmanMoved,
    ScoreChanged,
    ScreenChanged,
    TimeChanged,
)

__all__ = [
    "Back",
    "Backspace",
    "Cheat",
    "CheatsChanged",
    "Command",
    "Confirm",
    "Direction",
    "Event",
    "FoodCollected",
    "FoodSpawned",
    "FoodType",
    "GameOver",
    "GameWon",
    "GhostMoved",
    "GhostState",
    "GhostStateChanged",
    "HighscoresChanged",
    "LevelCompleted",
    "LevelStarted",
    "LivesChanged",
    "MazeGenerated",
    "MenuChanged",
    "MoveSelection",
    "NameEntryChanged",
    "PacmanCaught",
    "PacmanMoved",
    "Quit",
    "ScoreChanged",
    "Screen",
    "ScreenChanged",
    "SetDirection",
    "TimeChanged",
    "ToggleCheatMode",
    "TypeCharacter",
    "UseCheat",
]
