import asyncio                          # async/await event loop
import json                             # JSON serialization/deserialization
import os                               # environment variables
import time                             # time.time() for loop timing
from contextlib import asynccontextmanager  # decorator for lifespan management
from typing import Literal, Optional, Set , Union   # type hints
from fastapi import FastAPI, WebSocket, WebSocketDisconnect  # web framework + WS support
from pydantic import BaseModel     # data validation library
from jose import jwt               # jose is a python library used to work with jwt tokens
import httpx                       # async HTTP client — used to call auth-service REST API

# =============================================================================
# INPUT VALIDATION with PYDANTIC
# Pydantic models validate incoming JSON messages from the client.
# If a message doesn't match the expected shape, Pydantic raises ValidationError
# before our game logic ever runs.
# =============================================================================

class MovePayload(BaseModel):
    """
    Payload for a 'move' message sent by the client when a key is pressed or released.
    Direction is Optional because the client sends null on key release (stop movement).
    inputId is a increasing integer generated by the client,specific for that client,
    used for server reconciliation — the server echoes it back so the client
    knows which inputs have been processed.
    """
    direction: Optional[Literal["UP", "DOWN"]] = None  # "UP", "DOWN", or None (stop). It's the same of Union[Literal["UP","DOWN"], None] = None
    inputId: int                                        # client-side counter, starts at 0, resets on game start


class JoinLobbyPayload(BaseModel):
    """Payload for a 'joinLobby' message. Contains the player's chosen name."""
    playerName: str              # name of the player to add to the lobby coming from the frontend
    token: Optional[str] = None  # JWT from frontend for match recording

class StartGamePayload(BaseModel):
    """Payload for a 'startGame' message. vsAI flag defaults to False."""
    vsAI: bool = False  # if True, one slot is controlled by AI (if we want to implement that)


class ClientMessage(BaseModel):
    """
    Envelope for all messages received from the client.
    Every WebSocket message must have a 'type' field matching one of the
    accepted literals, and an optional 'payload' dict.
    The payload is kept as a raw dict here and validated separately inside
    each branch of the message handler, because each type has a different schema.
    """
    type: Literal["move", "joinLobby", "startGame", "voteAbandon", "restartGame", "backToLobby", "spectate", "leaveSpectator", "leaveLobby"]  # accepted message types
    payload: dict = {}  # raw dict, validated per-type in the handler


# =============================================================================
# GAME LOGIC
# =============================================================================

class Ball:
    """
    Represents the ball. Holds position, velocity, and radius — all normalized
    to the 0.0–1.0 coordinate space. The frontend multiplies by canvas dimensions
    to get pixel coordinates.
    Collision detection and goal checking are handled by PongGameState,
    because they depend on player positions.
    """

    def __init__(self): # all the values are merely indicative placeholders and will be validated once we have a functional game 
        self.x = 0.5        # horizontal position, normalized (0=left wall, 1=right wall)
        self.y = 0.5        # vertical position, normalized (0=top wall, 1=bottom wall)
        self.vx = 0.008     # horizontal velocity per tick (fraction of field width)
        self.vy = 0.004     # vertical velocity per tick (fraction of field height)
        self.radius = 0.013 # ball radius, normalized

    def update(self):
        """Advance ball position by one tick. Pure linear movement — no collision logic here."""
        self.x += self.vx   # move horizontally
        self.y += self.vy   # move vertically

    def reset(self):
        """
        Return ball to center after a goal.
        Inverts both velocity components so the next serve goes in the opposite direction.
        """
        self.x = 0.5        # back to center x
        self.y = 0.5        # back to center y
        self.vx = 0.008 if self.vx < 0 else -0.008   # reverse horizontal direction
        self.vy = 0.004 if self.vy < 0 else -0.004   # reverse vertical direction


    def serialize(self) -> dict:
        """
        Build the ball dict that goes into the gameState broadcast.
        Rounds to 4 decimal places to reduce payload size without losing precision.
        vx and vy are included so the frontend can interpolate ball position
        between server ticks for smooth rendering.
        """
        return {
            "x": round(self.x, 4),   # rounded position x
            "y": round(self.y, 4),   # rounded position y
            "vx": round(self.vx, 4), # velocity x — used by frontend for interpolation
            "vy": round(self.vy, 4), # velocity y — used by frontend for interpolation
            "radius": self.radius,   # constant, included to match frontend's expected schema
        }


class Player:
    """
    Represents one of the four paddles.
    Side determines orientation (left/right = vertical, top/bottom = horizontal)
    and initial position.
    Movement is applied every tick based on current_direction, which is updated
    when a 'move' message arrives — this gives smooth continuous movement instead
    of one-step-per-message movement.
    """

    def __init__(self, id: int, side: str, name: str = "Anonymous"):
        self.id = id                    # player slot index: 0=left, 1=right, 2=top, 3=bottom
        self.side = side                # "left" | "right" | "top" | "bottom"
        self.name = name                # display name, set on joinLobby
        self.score = 0                  # current score
        self.connected = False          # True only after joinLobby is received
        self.votedToAbandon = False     # True if this player has voted to abandon the game
        self.last_processed_input_id: int = -1          # last inputId received from this player, broadcasted for reconciliation
        self.current_direction: Optional[str] = None    # active movement direction, None = stopped.It's the same of Union[str, None] = None
        self.token: Optional[str] = None      # JWT for auth-service calls
        self.user_id: Optional[str] = None    # extracted from token payload
        
        # Set paddle dimensions and initial position based on side.
        if side in ["left", "right"]: # Same for ball,purely placeholders that need to be validated in game
            self.width = 0.015                              # paddle thickness (normalized)
            self.height = 0.13                              # paddle length (normalized)
            self.x = 0.02 if side == "left" else 0.965     # fixed X position near the wall
            self.y = 0.435                                  # initial Y: centered (0.5 - height/2)
        else:
            self.width = 0.13                               # paddle length (normalized)
            self.height = 0.015                             # paddle thickness (normalized)
            self.x = 0.435                                  # initial X: centered (0.5 - width/2)
            self.y = 0.02 if side == "top" else 0.965      # fixed Y position near the wall

    def move(self, speed: float = 0.02):
        """
        Apply one tick of movement based on current_direction.
        Called every tick by update_physics(), regardless of whether a new
        input has arrived — this is what makes movement smooth.
        If current_direction is None (key released), no movement is applied.
        For horizontal paddles, UP maps to left and DOWN maps to right.
        max/min clamp the position so the paddle never goes out of bounds.
        """
        direction = self.current_direction  # read current state
        if direction is None:               # no key held down, do nothing
            return

        if self.side in ["left", "right"]:          # vertical paddle: move on Y axis
            if direction == "UP":
                self.y = max(0, self.y - speed)             # clamp to top wall
            elif direction == "DOWN":
                self.y = min(1 - self.height, self.y + speed)  # clamp to bottom wall

        elif self.side in ["top", "bottom"]:        # horizontal paddle: move on X axis
            if direction == "UP":                   # UP = move left for horizontal paddles
                self.x = max(0, self.x - speed)             # clamp to left wall
            elif direction == "DOWN":               # DOWN = move right for horizontal paddles
                self.x = min(1 - self.width, self.x + speed)   # clamp to right wall

    def serialize(self) -> dict:
        """
        Build the player dict that goes into the gameState broadcast.
        lastProcessedInputId is echoed back to the client for server reconciliation:
        the client uses it to know which of its pending predicted inputs have been
        confirmed by the server, and reapplies the remaining ones on top of the
        authoritative position.
        """
        return {
            "id": self.id,                                  # player slot index: 0=left, 1=right, 2=top, 3=bottom
            "side": self.side,                              # "left" | "right" | "top" | "bottom"
            "x": round(self.x, 4),                          # rounded position x
            "y": round(self.y, 4),                          # rounded position y
            "width": self.width,                            # paddle width (constant)
            "height": self.height,                          # paddle height (constant)
            "score": self.score,                            # current score
            "connected": self.connected,                    # whether this slot has an active player
            "name": self.name,                              # display name
            "lastProcessedInputId": self.last_processed_input_id,  # for client-side reconciliation
            "votedToAbandon": self.votedToAbandon,          # abandon vote flag
        }


class PongGameState:
    """
    Single source of truth for the entire game.
    Holds ball, all four player slots, connection set, and game status.
    Responsible for physics update, collision detection, goal detection,
    and building the broadcast payload.
    """

    def __init__(self):
        self.status: Literal["waiting", "playing", "paused", "finished"] = "waiting"     # "waiting" | "countdown" | "playing" | "finished"
        self.tick = 0               # increments every physics update, used for reconciliation timing
        self.winner = None          # player id of the winner, None during play
        self.ball = Ball()          # single ball instance
        self.players = [            # four fixed slots, one per side — list literal
            Player(0, "left"),
            Player(1, "right"),
            Player(2, "top"),
            Player(3, "bottom"),
        ]
        self.spectators = []        # list of spectator dicts {"name" key : name value} , will be broadcasted to clients
        self.spectator_connections: dict = {}       # maps ws -> name, keeps track of spectator WebSocket connections for disconnect handling            
        self.connections: Set[WebSocket] = set()    # set of all active WebSocket connections
        self.lobby_queue: list = []  # list of dicts {"name": str, "ws": WebSocket, "user_id": str} waiting for a slot
        self.ws_to_player: dict = {}  # maps ws -> Player, used to promote queued clients on disconnect
        self.last_activity_time = time.time()  # timestamp of last physics tick — used to detect inactivity and trigger auto-reset
        self.slot_lock = asyncio.Lock()         # asyncio lock to prevent race conditions when assigning player slots on rapid reconnect

    def get_free_slot(self) -> Optional["Player"]:
        """
        Return the first player slot that is not connected, or None if all are taken.
        Uses a generator expression inside next() — iterates lazily and stops
        at the first match without scanning the whole list.
        """
        return next((p for p in self.players if not p.connected), None)  # generator expression

    async def update_physics(self):
        """
        Advance the game by one tick.
        Order matters: move ball first, then check collisions (so we can correct
        the position immediately after penetration), then check goals, then move paddles.
        """
        self.tick += 1          # increment tick counter
        self.ball.update()      # move ball by vx/vy
        self.check_collisions() # detect and resolve paddle-ball collisions
        await self.check_goal()       # detect if ball exited the field
        for player in self.players:  # move all paddles based on their current_direction
            player.move()

    def check_collisions(self):
        """
        AABB (Axis-Aligned Bounding Box) collision detection between ball and each paddle.
        For each connected player, checks if the ball's bounding circle overlaps
        the paddle rectangle. On hit: reverses the relevant velocity component,
        multiplies speed by 1.1 (acceleration), corrects ball position to prevent
        tunneling, and applies angular bounce based on impact point.
        """
        ball = self.ball

        for p in self.players:
            if not p.connected:     # skip disconnected slots
                continue

            # Compute paddle edges
            p_left   = p.x                  # left edge of paddle
            p_right  = p.x + p.width        # right edge of paddle
            p_top    = p.y                  # top edge of paddle
            p_bottom = p.y + p.height       # bottom edge of paddle

            # AABB check: ball circle overlaps paddle rectangle on both axes
            if (ball.x + ball.radius > p_left   and   # ball right side past paddle left edge
                ball.x - ball.radius < p_right  and   # ball left side before paddle right edge
                ball.y + ball.radius > p_top    and   # ball bottom past paddle top edge
                    ball.y - ball.radius < p_bottom): # ball top before paddle bottom edge

                # Resolve collision based on which wall the paddle is on
                if p.side == "left":
                    ball.vx = abs(ball.vx) * 1.1        # force vx positive (ball goes right) + accelerate
                    ball.x = p_right + ball.radius      # push ball outside paddle right edge (prevent tunneling)
                elif p.side == "right":
                    ball.vx = -abs(ball.vx) * 1.1       # force vx negative (ball goes left) + accelerate
                    ball.x = p_left - ball.radius       # push ball outside paddle left edge
                elif p.side == "top":
                    ball.vy = abs(ball.vy) * 1.1        # force vy positive (ball goes down) + accelerate
                    ball.y = p_bottom + ball.radius     # push ball outside paddle bottom edge
                elif p.side == "bottom":
                    ball.vy = -abs(ball.vy) * 1.1       # force vy negative (ball goes up) + accelerate
                    ball.y = p_top - ball.radius        # push ball outside paddle top edge

                self.apply_angular_bounce(p, ball)      # add angle variation based on impact point

    def apply_angular_bounce(self, player: "Player", ball: Ball):
        """
        Modify ball trajectory based on where it hits the paddle.
        Impact at the center - no angle change.
        Impact at the edges - steeper angle.
        Relative intersect is the normalized distance between impact point and paddle center.
        The multiplier (0.01) controls how extreme the angle effect is,for now purely a placeholder to be validated.
        """
        if player.side in ["left", "right"]:
            paddle_center = player.y + (player.height / 2)             # Y center of paddle
            relative_intersect = (ball.y - paddle_center) / player.height  # -0.5 to 0.5
            ball.vy += relative_intersect * 0.01                        # push vy based on impact point
        else:
            paddle_center = player.x + (player.width / 2)              # X center of paddle
            relative_intersect = (ball.x - paddle_center) / player.width   # -0.5 to 0.5
            ball.vx += relative_intersect * 0.01                        # push vx based on impact point

    async def check_goal(self):
        """
        Detect if the ball has entirely exited the field (past any wall).
        Awards one point to all players except the loser.
        Resets the ball to center after a goal.
        Returns early if no goal has occurred (guard clause).
        """
        ball = self.ball
        margin = ball.radius    # use radius as tolerance so goal triggers when ball is fully outside

        # Guard clause: if ball is still inside the field, do nothing
        if not (ball.x < -margin or ball.x > 1 + margin or
                ball.y < -margin or ball.y > 1 + margin):
            return

        # Determine exit side
        if ball.x < 0:
            exit_side = "left"
        elif ball.x > 1:
            exit_side = "right"
        elif ball.y < 0:
            exit_side = "top"
        else:
            exit_side = "bottom"

        # Check if that side has a connected player
        side_has_player = any(
            p.side == exit_side and p.connected
            for p in self.players
        )                                           # generator expression: True if a connected player owns that side

        if side_has_player:                         # goal: award points to all connected players on other sides
            for p in self.players:
                if p.side != exit_side and p.connected:  # only connected players score — disconnected Anonymous slots are excluded
                    p.score += 1
            ball.reset()
            await self.emit_event("score", {
                "missedSide": exit_side,
                "scoringPlayers": [
                    {"id": p.id, "name": p.name, "score": p.score}
                    for p in self.players if p.side != exit_side
                ],
            })
            await self.check_winner()

        else:                                       # no player on that side: bounce instead of scoring                                   
            if exit_side == "left":
                ball.vx = abs(ball.vx)              # force positive (ball goes right)
                ball.x = ball.radius               # prevent tunneling : push ball just inside left wall
            elif exit_side == "right":
                ball.vx = -abs(ball.vx)            # force negative (ball goes left)
                ball.x = 1 - ball.radius           # prevent tunneling : push ball just inside right wall
            elif exit_side == "top":
                ball.vy = abs(ball.vy)             # force positive (ball goes down)
                ball.y = ball.radius               # prevent tunneling : push ball just inside top wall
            elif exit_side == "bottom":
                ball.vy = -abs(ball.vy)            # force negative (ball goes up)
                ball.y = 1 - ball.radius           # prevent tunneling : push ball just inside bottom wall    
                
    async def check_winner(self):
        """
        Check if any player has reached the winning score (first to 10).
        If so, set game status to finished, record the winner,
        and broadcast a gameOver event.
        Winning score is hardcoded to 10 — move to a config constant later.
        """
        for p in self.players:
            if p.score >= 10:                        # winning condition
                self.status = "finished"            # stop the game loop from advancing physics
                self.last_activity_time = time.time()  # record finish time for inactivity timeout
                self.winner = p.id                  # record winner id
                await self.emit_event("gameOver", { # notify all clients
                    "winner": p.id,                 # winner's slot id
                    "finalScores": [                # list comprehension: all players' final scores
                        {"id": pl.id, "name": pl.name, "score": pl.score}
                        for pl in self.players
                    ],
                })
                try:
                    async with httpx.AsyncClient(verify=False) as client: # sends a POST request to the auth service for the match logging
                        connected_players = [pl for pl in self.players if pl.connected]
                        body = {    # in case of 2 players
                            "player1_id": connected_players[0].user_id,
                            "player2_id": connected_players[1].user_id,
                            "winner_id": p.user_id,              # p is the loop winner
                            "score_player1": connected_players[0].score,
                            "score_player2": connected_players[1].score,
                        }
                        if len(connected_players) >= 3: # 3 players
                            body["player3_id"] = connected_players[2].user_id
                            body["score_player3"] = connected_players[2].score
                        if len(connected_players) == 4: # 4 players
                            body["player4_id"] = connected_players[3].user_id
                            body["score_player4"] = connected_players[3].score
                        _auth_host = os.getenv("AUTH_SERVICE_HOST", "auth-service")   # read from env, fallback to docker service name
                        _auth_port = os.getenv("AUTH_SERVICE_INTERNAL_PORT", "8000")  # read from env, fallback to internal port
                        await client.post(
                            f"https://{_auth_host}:{_auth_port}/api/v1/matches/", # API url
                            json=body,
                            headers={"Authorization": f"Bearer {p.token}"} # sends the winner's token to the auth service
                        )
                except Exception as e:
                    print(f"⚠️  Failed to record match to auth-service: {e}")  # non-fatal: game continues even if logging fails
                return                              # stop checking after first winner found

    async def reset(self):
        """
        Reset the entire game state back to waiting status.
        Called after gameAbandoned or restartGame.
        Resets ball, all player slots, tick counter and winner.
        Does NOT clear connections — clients stay connected to the WebSocket,
        they just need to send joinLobby again to re-enter the game.
        """
        self.status = "waiting"     # back to initial status
        self.tick = 0               # reset tick counter
        self.winner = None          # clear winner

        self.ball.x = 0.5           # reset ball to center x
        self.ball.y = 0.5           # reset ball to center y
        self.ball.vx = 0.008        # reset ball horizontal velocity
        self.ball.vy = 0.004        # reset ball vertical velocity
        self.lobby_queue.clear()    # clear waiting queue on reset
        self.ws_to_player.clear()   # clear dict ws -> Player on reset
        self.spectator_connections.clear()  # clear spectator ws -> name map on reset
        self.spectators = []  # clear serialized spectator list on reset
        

        for p in self.players:                  # iterate all four slots
            p.score = 0                         # reset score
            p.connected = False                 # free the slot
            p.name = "Anonymous"               # clear name
            p.votedToAbandon = False           # clear abandon vote
            p.current_direction = None         # stop any movement
            p.last_processed_input_id = -1     # reset reconciliation counter
            p.token = None                     # reset jwt 
            p.user_id = None                   # reset uuid

            if p.side in ["left", "right"]:    # restore initial Y position for vertical paddles
                p.y = 0.435
            else:                              # restore initial X position for horizontal paddles
                p.x = 0.435

    async def restart_match(self):
        """
        Restart the match immediately without returning to the lobby.
        Unlike reset(), keeps all currently connected players in their slots
        and transitions directly to playing status — used by the 'Play Again' flow.
        Only resets score, ball, tick and movement state for connected players.
        """
        self.status = "playing"     # transition directly to playing, skipping the lobby
        self.tick = 0               # reset tick counter
        self.winner = None          # clear previous winner

        self.ball.x = 0.5           # reset ball to center x
        self.ball.y = 0.5           # reset ball to center y
        self.ball.vx = 0.008        # reset ball horizontal velocity
        self.ball.vy = 0.004        # reset ball vertical velocity

        for p in self.players:
            if p.connected:         # only reset connected players — disconnected slots are left untouched
                p.score = 0                         # reset score
                p.votedToAbandon = False            # clear abandon vote
                p.current_direction = None          # stop any ongoing movement
                p.last_processed_input_id = -1      # reset reconciliation counter
                if p.side in ["left", "right"]:
                    p.y = 0.435                     # restore initial Y for vertical paddles
                else:
                    p.x = 0.435                     # restore initial X for horizontal paddles

    async def emit_event(self, event_type: str, data: dict):
        """
        Broadcast a gameEvent message to all connected clients.
        gameEvent is a one-shot notification for discrete game moments
        (score, gameStart, gameOver) as opposed to the continuous gameState broadcast.
        data contains event-specific information defined per event_type.
        """
        await broadcast("gameEvent", {  # reuse broadcast utility for all clients
            "type": event_type,         # event identifier: "score" | "gameStart" | "gameOver" | "gameAbandoned"| "gameReset"| "playerReconnected"
            "data": data,               # event-specific payload
        })       
    
    async def promote_from_queue(self):
        """
        Promote the first client in lobby_queue to a free player slot.
        Called when a player disconnects and frees a slot.
        Sends playerAssigned to the promoted client and updates lobby.
        """
        if not self.lobby_queue:                        # nothing to promote
            return
        free_slot = self.get_free_slot()               # check if there is a free slot
        if not free_slot:                              # no free slot available
            return
        entry = self.lobby_queue.pop(0)                # take first in queue — pop(0) removes and returns first element,a dict with {"name": str, "ws" : Websocket}
        free_slot.connected = True                     # mark slot as occupied
        free_slot.name = entry["name"]                 # assign name
        self.ws_to_player[entry["ws"]] = free_slot     # register new ws -> player mapping
        free_slot.user_id = entry.get("user_id")       # restore user_id from queue entry for auth-service match recording
        free_slot.token = entry.get("token")           # restore JWT token
        await send_to(entry["ws"], "lobbyJoined", {"name": entry["name"]})  # notify promoted client he joined the lobby
        await send_to(entry["ws"], "playerAssigned", { # notify promoted client he was assigned to a Player slot
            "playerId": free_slot.id,
            "user_id" : free_slot.user_id,
            "side": free_slot.side,
            "name": free_slot.name,
            "roomId": "main",
            "gameStatus": self.status,
        })

    def get_payload(self) -> dict:
        """
        Build the full gameState message dict ready for json.dumps().
        This is broadcast to all connected clients every tick.
        Structure matches the frontend's expected schema from GameState.js serialize().
        """
        return {
            "type": "gameState",    # message type identifier, read by frontend's message handler
            "payload": {
                "status": self.status,          # current game phase
                "tick": self.tick,              # tick counter for reconciliation timing
                "winner": self.winner,          # None during play, player id when finished
                "activePlayerCount": sum(1 for p in self.players if p.connected),  # generator expression inside sum()
                "aiEnabled": False,             # AI mode not yet implemented
                "aiPlayerSlot": None,           # AI slot not yet implemented
                "ball": self.ball.serialize(),  # ball position and velocity
                "players": [p.serialize() for p in self.players],  # list comprehension: serialize all 4 slots in one line
                "spectators": self.spectators,  # list of spectators dicts {"name" : str}
                "lobby": {"playersReady": []},  # lobby state, work in progress
            },
        }

    def get_lobby_state(self) -> dict:
        """
        Build the lobby state dict broadcast to all clients after every joinLobby.
        Contains the list of connected players, spectators, and canStart flag.
        canStart is True when at least 2 players are connected — matches the
        frontend's MIN_PLAYERS_TO_START logic in GameState.js canStartGame().
        """
        connected = [p for p in self.players if p.connected]   # list comprehension: only connected slots
        return {
            "players": [{"name": p.name} for p in connected] +  # list comprehension: name needed in lobby
           [{"name": e["name"]} for e in self.lobby_queue],         # include queued players
            "spectators": self.spectators,                      # spectator list (empty until implemented)
            "canStart": len(connected) >= 2,                    # True when minimum players are present
        }


# =============================================================================
# SERVER CORE
# =============================================================================

game = PongGameState()  # single global game instance (one room)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    FastAPI lifespan context manager.
    Starts the world loop as a background task on server startup,
    cancels it cleanly on shutdown.
    """
    task = asyncio.create_task(world_loop())    # start game loop in background
    yield                                       # server runs here
    task.cancel()                               # cancel loop on shutdown


app = FastAPI(lifespan=lifespan)    # FastAPI instance with lifespan handler


async def world_loop():
    """
    Main game loop. Runs at 60fps.
    On each iteration:
      1. If game is playing, advance physics by one tick
      2. Serialize current game state to JSON string (once, reused for all clients)
      3. Broadcast to all connected clients concurrently using asyncio.gather
      4. Sleep for the remaining time to maintain 60fps cadence
    Serializing once and reusing the string avoids redundant work when
    there are multiple connected clients.
    """
    loop_time = 1 / 60  # target interval in seconds (~16.6ms)

    while True:
        start = time.time()                         # record tick start time

        if game.status == "playing":
            await game.update_physics()                   # advance ball and paddles
            game.last_activity_time = start               # update activity timestamp on every physics tick
        elif game.status in ["paused", "finished"]:
            # inactivity timeout: if game has been paused or finished for more than 15 seconds
            # with no activity, auto-reset to waiting and notify all clients
            if start - game.last_activity_time > 15:
                await game.reset()
                game.last_activity_time = time.time()  # reset activity timestamp to avoid immediate re-trigger
                await broadcast("lobbyUpdate", game.get_lobby_state())
                await game.emit_event("gameReset", {"reason": "timeout"})
                continue                               # skip broadcast this tick, state is already reset
        payload_json = json.dumps(game.get_payload())   # serialize once for all clients

        if game.connections:
            await asyncio.gather(                   # send to all clients concurrently
                *[ws.send_text(payload_json) for ws in list(game.connections)],  # list comprehension builds coroutine list, * unpacks into gather
                  return_exceptions = True          # individual send failures are returned as values, not raised — prevents a dead WebSocket from crashing other clients
            )

        wait = loop_time - (time.time() - start)    # remaining time in this tick
        await asyncio.sleep(max(0, wait))           # sleep, clamped to 0 to avoid negative sleep


async def send_to(ws: WebSocket, type: str, payload: dict):
    """
    Send a single typed JSON message to one client.
    Wraps the message in the standard { type, payload } envelope.
    Used for one-off messages (playerAssigned, error, etc.) as opposed
    to the broadcast in world_loop which uses send_text directly.
    """
    await ws.send_text(json.dumps({"type": type, "payload": payload}))


async def broadcast(type: str, payload: dict):
    """
    Utility: send a single typed JSON message to ALL connected clients.
    Used for events that all clients need to receive simultaneously,
    such as lobbyUpdate — as opposed to send_to which targets one client.
    Reuses the same serialized string for all clients to avoid redundant work.
    return_exceptions=True prevents a single dead WebSocket from propagating
    an exception into the caller's coroutine and accidentally disconnecting other players.
    """
    msg = json.dumps({"type": type, "payload": payload})    # serialize once for all recipients
    if game.connections:
        await asyncio.gather(                               # send concurrently to all clients
            *[ws.send_text(msg) for ws in list(game.connections)],  # list comprehension unpacked into gather
              return_exceptions = True  # dead WebSocket failures are silently ignored — they will be cleaned up by their own coroutine's except block
        )


@app.websocket("/ws")
async def websocket_endpoint(ws: WebSocket):
    """
    WebSocket connection handler. One coroutine instance runs per connected client.
    Accepts the connection, adds it to the global connections set,
    then loops waiting for messages.
    'player' starts as None and is assigned when joinLobby is received —
    initialized here so the except block can safely reference it even if
    the client disconnects before sending joinLobby.
    On disconnect or any exception, marks the player as disconnected,
    broadcasts the updated lobby state to remaining clients and
    removes the socket from the connections set.
    """
    await ws.accept()               # complete WebSocket handshake
    game.connections.add(ws)        # register connection for broadcasts
    await ws.send_text(json.dumps({  # send current lobby state immediately on connect so the client doesn't wait for the next broadcast
        "type": "lobbyUpdate",
        "payload": game.get_lobby_state()
    }))
    player: Optional[Player] = None # will be assigned on joinLobby. Same of Union[Player, None] = None

    try:
        while True:
            data = await ws.receive_json()      # wait for next message, parsed as dict
            msg = ClientMessage(**data)         # validate envelope with Pydantic
            player = game.ws_to_player.get(ws)  # always read current player from shared map, picks up promotions

            if msg.type == "joinLobby":
                parsed = JoinLobbyPayload(**msg.payload)    # validate joinLobby-specific payload
                if not parsed.token:                        # token is required — unauthenticated clients cannot join as players
                    await send_to(ws, "error", {
                        "message": "Authentication required to join as player",
                        "code": "AUTH_REQUIRED",
                    })
                    continue

                try:
                    payload = jwt.get_unverified_claims(parsed.token)  # decode JWT payload without verifying signature — verification is auth-service's responsibility
                    if not payload.get("sub"):
                        raise ValueError("Missing sub claim")           # sub claim contains the user UUID
                except Exception:
                    await send_to(ws, "error", {                        # token is malformed or missing required claims
                        "message": "Invalid token",
                        "code": "INVALID_TOKEN",
                    })
                    continue

                token_user_id = payload.get("sub")  # extract user UUID from token payload

                # check if this user is already in the game or in the queue — identified by UUID, not by name
                already_connected = any(
                    p.user_id == token_user_id and p.connected
                    for p in game.players
                ) or any(
                    e.get("user_id") == token_user_id
                    for e in game.lobby_queue
                )

                if already_connected:               # same user cannot occupy two slots simultaneously
                    await send_to(ws, "error", {
                        "message": "You are already in the lobby",
                        "code": "ALREADY_CONNECTED",
                    })
                    continue

                # RECONNECTION LOGIC: if game is paused/playing/finished, only allow reconnecting to own slot
                reconnecting_player = next((p for p in game.players if p.user_id == token_user_id and not p.connected), None)
                
                if reconnecting_player:
                    player = reconnecting_player
                    player.connected = True
                    player.name = parsed.playerName # update display name in case it changed
                    game.ws_to_player[ws] = player
                    player.token = parsed.token
                    await send_to(ws, "lobbyJoined", {"name": player.name})  # confirm lobby entry before slot assignment
                    await send_to(ws, "playerAssigned", {   # confirm assignment to this client
                        "playerId": player.id,
                        "side": player.side,
                        "name": player.name,
                        "roomId": "main",
                        "gameStatus": game.status,
                    })
                    
                    # check if all original players are reconnected to resume the game
                    disconn_players = [p for p in game.players if p.user_id is not None and not p.connected]
                    if not disconn_players and game.status == "paused":
                        game.status = "playing"
                        game.last_activity_time = time.time()
                        await game.emit_event("gameResumed", {
                            "playerCount": sum(1 for p in game.players if p.connected),
                        })
                    
                    await broadcast("lobbyUpdate", game.get_lobby_state())  # notify ALL clients of updated lobby
                    continue
                else:
                    # New player joining
                    if game.status in ["playing", "paused", "finished"]:
                        # cannot join as new player during active/paused/finished match, assign spectator
                        game.spectator_connections[ws] = parsed.playerName
                        game.spectators = [
                            {"name": n} for n in game.spectator_connections.values()
                        ]
                        await send_to(ws, "spectatorAssigned", {"name": parsed.playerName})
                        await broadcast("lobbyUpdate", game.get_lobby_state())
                    else:
                        player = game.get_free_slot()
                        if player: # slot available and game is waiting
                            player.connected = True                 # mark slot as occupied
                            player.name = parsed.playerName         # set display name
                            game.ws_to_player[ws] = player          # register ws -> player mapping for queue promotion and ownership checks
                            player.token = parsed.token             # saves the jwt token for auth-service match recording
                            player.user_id = payload.get("sub")     # store user UUID for duplicate detection and match recording
                            await send_to(ws, "lobbyJoined", {"name": player.name})  # confirm lobby entry before slot assignment
                            await send_to(ws, "playerAssigned", {   # confirm assignment to this client
                                "playerId": player.id,
                                "side": player.side,
                                "name": player.name,
                                "roomId": "main",                   # to be defined
                                "gameStatus": game.status,
                            })
                            await broadcast("lobbyUpdate", game.get_lobby_state())  # notify ALL clients of updated lobby
                        else:
                            # game not in progress, all slots taken — add to waiting queue
                            game.lobby_queue.append({"name": parsed.playerName, "ws": ws, "user_id": token_user_id, "token": parsed.token})  # store name, ws and uuid for promotion
                            await send_to(ws, "lobbyJoined", {"name": parsed.playerName})         # confirm lobby entry
                            await broadcast("lobbyUpdate", game.get_lobby_state())               # notify all clients of queue update

            elif msg.type == "startGame":
                was_paused = game.status == "paused"        # detect if resuming from pause rather than starting fresh
                game.status = "playing"                     # transition game to playing state
                game.last_activity_time = time.time()       # reset inactivity timer on game start
                if was_paused:
                    await game.emit_event("gameResumed", {  # notify clients that a paused game is resuming — different from a fresh start
                        "playerCount": sum(1 for p in game.players if p.connected),
                    })
                else:
                    await game.emit_event("gameStart", {    # notify all clients the game has started fresh
                        "playerCount": sum(1 for p in game.players if p.connected),  # generator expression: count connected players
                    })

            elif msg.type == "move":
                parsed = MovePayload(**msg.payload)         # validate move payload
                if player:
                    player.current_direction = parsed.direction         # saves current direction (None = stop),so the function move reads the direction and moves the paddle until None arrives: this guarantees smooth paddle movement
                    player.last_processed_input_id = parsed.inputId     # record for reconciliation echo

            elif msg.type == "voteAbandon":
                if player:
                    player.votedToAbandon = True                                   # flag this player's abandon vote
                    connected = [p for p in game.players if p.connected]           # list comprehension: only active players
                    votes = sum(1 for p in connected if p.votedToAbandon)          # generator expression: count votes
                    if votes == len(connected):                                    # all connected players voted
                        await game.reset()                                         # reset game state
                        await game.emit_event("gameAbandoned", {                   # notify all clients
                            "reason": "All players voted to abandon",              # reason string
                        })
                        await broadcast("lobbyUpdate", game.get_lobby_state())      # force clients to refresh lobby lists

            elif msg.type == "spectate":
                name = msg.payload.get("name", "Spectator")                 # get name from payload, default to "Spectator"
                game.spectator_connections[ws] = name                       # register spectator ws -> name
                game.spectators = [                                         # rebuild serializable spectators list
                    {"name": n} for n in game.spectator_connections.values()  # list comprehension: only names for broadcast
                ]
                await send_to(ws, "spectatorAssigned", {"name": name})      # confirm to this client only
                await broadcast("lobbyUpdate", game.get_lobby_state())      # notify all clients of new spectator

            elif msg.type == "leaveSpectator":
                if ws in game.spectator_connections:                         # only act if this ws is actually registered as a spectator
                    del game.spectator_connections[ws]                       # remove spectator from tracking dict
                    game.spectators = [                                      # rebuild serializable spectator list without this client
                        {"name": n} for n in game.spectator_connections.values()
                    ]
                    await broadcast("lobbyUpdate", game.get_lobby_state())   # notify all clients that spectator left

            elif msg.type == "leaveLobby":
                if player:                              # only clean up if this ws was registered as a player
                    player.connected = False            # free the slot
                    player.current_direction = None     # stop any ongoing movement
                    player.name = "Anonymous"           # clear display name
                    player.score = 0                    # reset score
                    player.token = None                 # clear JWT
                    player.user_id = None               # clear UUID so the slot is fully available
                    player.votedToAbandon = False        # clear abandon vote
                game.ws_to_player.pop(ws, None)                             # remove ws -> player mapping
                game.lobby_queue = [e for e in game.lobby_queue if e["ws"] != ws]  # remove from queue if present
                await game.promote_from_queue()                             # fill freed slot from queue if available
                await broadcast("lobbyUpdate", game.get_lobby_state())      # notify all clients
            
            elif msg.type == "restartGame":
                await game.restart_match()                  # reset scores and ball, keep connected players in their slots
                await game.emit_event("gameStart", {        # notify all clients that a new match is starting immediately
                    "playerCount": sum(1 for p in game.players if p.connected),
                })

            elif msg.type == "backToLobby":
                if not player:                              # only active players can trigger a lobby reset
                    await send_to(ws, "error", {
                        "message": "Only active players can reset match to lobby",
                        "code": "BACK_TO_LOBBY_NOT_PLAYER",
                    })
                    continue
                if game.status != "finished":               # back to lobby is only valid after a match has ended
                    await send_to(ws, "error", {
                        "message": "Back to lobby is available only after match end",
                        "code": "BACK_TO_LOBBY_NOT_FINISHED",
                    })
                    continue
                await game.reset()                                          # full reset: disconnect all players, clear all state
                await game.emit_event("gameReset", {})                      # notify all clients to reset their local state
                await broadcast("lobbyUpdate", game.get_lobby_state())      # notify all clients of empty lobby

    except (WebSocketDisconnect, Exception):
        if player and game.ws_to_player.get(ws) == player:
            # verify ownership before clearing: if the client refreshed rapidly, the new connection
            # may have already taken this player slot — in that case ws_to_player[ws] no longer points
            # to this player, so we skip the cleanup to avoid overwriting the new session's state
            player.connected = False            # free up the slot
            player.current_direction = None     # stop any ongoing movement
            player.votedToAbandon = False        # clear abandon vote
            
            if game.status in ["playing", "paused", "finished"]:
                if game.status != "finished":
                    game.status = "paused"                      # pause the game so remaining players can wait for reconnection
                    game.last_activity_time = time.time()       # start inactivity timer from this moment
                await game.emit_event("playerDisconnected", {  # notify remaining clients that a player left
                    "playerId": player.id,
                    "name": player.name
                })
            else:
                player.token = None                 # clear JWT
                player.user_id = None               # clear UUID so the slot is available for reconnection
                # only clear name if not in an active match, so disconnected players retain their name on the canvas
                player.name = "Anonymous"           # clear display name
        game.ws_to_player.pop(ws, None)                # remove ws -> player mapping, pop with None avoids KeyError
        if ws in game.spectator_connections:            # check if disconnected client was a spectator
            del game.spectator_connections[ws]          # remove key from spectator dict
            game.spectators = [                         # rebuild serializable list iterating on values
                {"name": n} for n in game.spectator_connections.values()
            ]
        game.connections.discard(ws)                    # discard (unlike remove, doesn't raise error if not present)
        game.lobby_queue = [e for e in game.lobby_queue if e["ws"] != ws]  # remove disconnected client from queue
        if game.status not in ["playing", "paused"]:
            await game.promote_from_queue()             # promote first in queue if slot is free — skipped during active game
        await broadcast("lobbyUpdate", game.get_lobby_state())  # notify remaining clients that a player left
