# Configurazione completa per i test automatici

server {
    listen 127.0.0.1:8080;
    server_name www.local;
    root ./var/www/html;
    error_page 404 /404.html;
    error_page 500 /500.html;
    client_max_body_size 1000000;

    location / {
        root ./var/www/html;
        index index.html;
        autoindex off;
        allowed_methods GET POST;
    }

    location /autoindex {
        root ./var/www/autoindex;
        autoindex on;
        allowed_methods GET;
    }

    location /upload {
        root ./var/www/upload;
        autoindex off;
        allowed_methods POST DELETE;
        upload_store ./var/www/upload;
    }

    location /cgi-bin {
        root ./var/www/cgi-bin;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
        allowed_methods GET POST;
    }

    location /oldpage {
        redirect /newpage;
    }

    location /newpage {
        root ./var/www/html;
        index newpage.html;
        allowed_methods GET;
    }
}

server {
    listen 127.0.0.1:8080;
    server_name api.local;
    root ./var/www/api;
    error_page 404 /api404.html;

    location /v1/ {
        root ./var/www/api/v1;
        index index.json;
        autoindex off;
        allowed_methods GET;
    }
}
