.PHONY: install run debug clean lint lint-strict

install:
	uv sync

run:
	HF_HOME=$(HF_HOME) HF_TOKEN=$(HF_TOKEN) uv run python -m src

debug:
	uv run python -m pdb -m src

clean:
	rm -rf */__pycache__ */.mypy_cache data/output/
	uv cache clean

lint:
	uv run flake8 src/
	uv run mypy src/ --warn-return-any --warn-unused-ignores --ignore-missing-imports --disallow-untyped-defs --check-untyped-defs

lint-strict:
	uv run flake8 src/
	uv run mypy src/ --strict
