NAME		= libftprintf.a

CC			= cc
CFLAGS		= -Wall -Wextra -Werror

SRC			=	ft_printf.c \
				ft_printf_fnorm.c \

OBJ			= $(SRC:.c=.o)

HEADER		= ft_printf.h

all: $(NAME)

$(NAME): $(OBJ)
	ar rcs $(NAME) $(OBJ)

%.o: %.c $(HEADER)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re