server {
    listen 443 ssl;
    server_name tlukan.42.fr;

    # Certificati TLS
    ssl_certificate     /etc/ssl/certs/inception.crt;
    ssl_certificate_key /etc/ssl/private/inception.key;

    # Solo TLSv1.2 e TLSv1.3 — REQUISITO DEL SUBJECT
    ssl_protocols TLSv1.2 TLSv1.3;

    # Directory radice del sito
    root  /var/www/html;
    index index.php index.html;

    # Gestione file statici
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Passa le richieste PHP a WordPress+php-fpm sulla porta 9000
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}