# Generated by Django 5.2.14 on 2026-05-05 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('accepted', 'Accettato'), ('badge', 'Badge'), ('read', 'Letto')], max_length=100, null=True)),
                ('event_id', models.CharField(blank=True, null=True)),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_got_notificated', to='accounts.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('games', models.IntegerField(default=0)),
                ('victories', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('wins_in_a_row', models.IntegerField(default=0)),
                ('single_player_games', models.IntegerField(default=0)),
                ('multiplayer_games', models.IntegerField(default=0)),
                ('consecutive_correct_answers', models.IntegerField(default=0)),
                ('highest_streak', models.IntegerField(default=0)),
                ('badges', models.ManyToManyField(to='accounts.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
