# Generated by Django 5.2.15 on 2026-06-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistic",
            name="lifeline_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="statistic",
            name="mp_correct_answers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="statistic",
            name="sp_correct_answers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="statistic",
            name="tournament_wins",
            field=models.IntegerField(default=0),
        ),
    ]
