# Generated by Django 4.2.30 on 2026-06-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
