# Generated by Django 5.2.15 on 2026-06-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notification_event_id'),
        ('core', '0003_statistic_lifeline_used_statistic_mp_correct_answers_and_more'),
    ]

    operations = [
    ]
