import asyncio                          # async/await event loop
import json                             # JSON serialization/deserialization
import time                             # time.time() for loop timing
from contextlib import asynccontextmanager  # decorator for lifespan management
from typing import Literal, Optional, Set   # type hints
from fastapi import FastAPI, WebSocket, WebSocketDisconnect  # web framework + WS support
from pydantic import BaseModel          # data validation library


# =============================================================================
# INPUT VALIDATION with PYDANTIC
# Pydantic models validate incoming JSON messages from the client.
# If a message doesn't match the expected shape, Pydantic raises ValidationError
# before our game logic ever runs.
# =============================================================================

class MovePayload(BaseModel):
    """
    Payload for a 'move' message sent by the client when a key is pressed or released.
    Direction is Optional because the client sends null on key release (stop movement).
    inputId is a increasing integer generated by the client,specific for that client,
    used for server reconciliation — the server echoes it back so the client
    knows which inputs have been processed.
    """
    direction: Optional[Literal["UP", "DOWN"]] = None  # "UP", "DOWN", or None (stop). It's the same of Union[Literal["UP","DOWN"], None] = None
    inputId: int                                        # client-side counter, starts at 0, resets on game start


class JoinLobbyPayload(BaseModel):
    """Payload for a 'joinLobby' message. Contains the player's chosen name."""
    playerName: str


class StartGamePayload(BaseModel):
    """Payload for a 'startGame' message. vsAI flag defaults to False."""
    vsAI: bool = False  # if True, one slot is controlled by AI (if we want to implement that)


class ClientMessage(BaseModel):
    """
    Envelope for all messages received from the client.
    Every WebSocket message must have a 'type' field matching one of the
    accepted literals, and an optional 'payload' dict.
    The payload is kept as a raw dict here and validated separately inside
    each branch of the message handler, because each type has a different schema.
    """
    type: Literal["move", "joinLobby", "startGame", "voteAbandon", "restartGame", "spectate"]  # accepted message types
    payload: dict = {}  # raw dict, validated per-type in the handler


# =============================================================================
# GAME LOGIC
# =============================================================================

class Ball:
    """
    Represents the ball. Holds position, velocity, and radius — all normalized
    to the 0.0–1.0 coordinate space. The frontend multiplies by canvas dimensions
    to get pixel coordinates.
    Collision detection and goal checking are handled by PongGameState,
    because they depend on player positions.
    """

    def __init__(self): # all the values are merely indicative placeholders and will be validated once we have a functional game 
        self.x = 0.5        # horizontal position, normalized (0=left wall, 1=right wall)
        self.y = 0.5        # vertical position, normalized (0=top wall, 1=bottom wall)
        self.vx = 0.008     # horizontal velocity per tick (fraction of field width)
        self.vy = 0.004     # vertical velocity per tick (fraction of field height)
        self.radius = 0.013 # ball radius, normalized

    def update(self):
        """Advance ball position by one tick. Pure linear movement — no collision logic here."""
        self.x += self.vx   # move horizontally
        self.y += self.vy   # move vertically

    def reset(self):
        """
        Return ball to center after a goal.
        Inverts both velocity components so the next serve goes in the opposite direction.
        """
        self.x = 0.5        # back to center x
        self.y = 0.5        # back to center y
        self.vx *= -1       # reverse horizontal direction
        self.vy *= -1       # reverse vertical direction

    def serialize(self) -> dict:
        """
        Build the ball dict that goes into the gameState broadcast.
        Rounds to 4 decimal places to reduce payload size without losing precision.
        vx and vy are included so the frontend can interpolate ball position
        between server ticks for smooth rendering.
        """
        return {
            "x": round(self.x, 4),   # rounded position x
            "y": round(self.y, 4),   # rounded position y
            "vx": round(self.vx, 4), # velocity x — used by frontend for interpolation
            "vy": round(self.vy, 4), # velocity y — used by frontend for interpolation
            "radius": self.radius,   # constant, included to match frontend's expected schema
        }


class Player:
    """
    Represents one of the four paddles.
    Side determines orientation (left/right = vertical, top/bottom = horizontal)
    and initial position.
    Movement is applied every tick based on current_direction, which is updated
    when a 'move' message arrives — this gives smooth continuous movement instead
    of one-step-per-message movement.
    """

    def __init__(self, id: int, side: str, name: str = "Anonymous"):
        self.id = id                    # player slot index: 0=left, 1=right, 2=top, 3=bottom
        self.side = side                # "left" | "right" | "top" | "bottom"
        self.name = name                # display name, set on joinLobby
        self.score = 0                  # current score
        self.connected = False          # True only after joinLobby is received
        self.votedToAbandon = False     # True if this player has voted to abandon the game
        self.last_processed_input_id: int = -1          # last inputId received from this player, broadcasted for reconciliation
        self.current_direction: Optional[str] = None    # active movement direction, None = stopped.It's the same of Union[str, None] = None

        # Set paddle dimensions and initial position based on side.
        if side in ["left", "right"]: # Same for ball,purely placeholders that need to be validated in game
            self.width = 0.015                              # paddle thickness (normalized)
            self.height = 0.13                              # paddle length (normalized)
            self.x = 0.02 if side == "left" else 0.965     # fixed X position near the wall
            self.y = 0.435                                  # initial Y: centered (0.5 - height/2)
        else:
            self.width = 0.13                               # paddle length (normalized)
            self.height = 0.015                             # paddle thickness (normalized)
            self.x = 0.435                                  # initial X: centered (0.5 - width/2)
            self.y = 0.02 if side == "top" else 0.965      # fixed Y position near the wall

    def move(self, speed: float = 0.02):
        """
        Apply one tick of movement based on current_direction.
        Called every tick by update_physics(), regardless of whether a new
        input has arrived — this is what makes movement smooth.
        If current_direction is None (key released), no movement is applied.
        For horizontal paddles, UP maps to left and DOWN maps to right.
        max/min clamp the position so the paddle never goes out of bounds.
        """
        direction = self.current_direction  # read current state
        if direction is None:               # no key held down, do nothing
            return

        if self.side in ["left", "right"]:          # vertical paddle: move on Y axis
            if direction == "UP":
                self.y = max(0, self.y - speed)             # clamp to top wall
            elif direction == "DOWN":
                self.y = min(1 - self.height, self.y + speed)  # clamp to bottom wall

        elif self.side in ["top", "bottom"]:        # horizontal paddle: move on X axis
            if direction == "UP":                   # UP = move left for horizontal paddles
                self.x = max(0, self.x - speed)             # clamp to left wall
            elif direction == "DOWN":               # DOWN = move right for horizontal paddles
                self.x = min(1 - self.width, self.x + speed)   # clamp to right wall

    def serialize(self) -> dict:
        """
        Build the player dict that goes into the gameState broadcast.
        lastProcessedInputId is echoed back to the client for server reconciliation:
        the client uses it to know which of its pending predicted inputs have been
        confirmed by the server, and reapplies the remaining ones on top of the
        authoritative position.
        """
        return {
            "id": self.id,                                  # player slot index: 0=left, 1=right, 2=top, 3=bottom
            "side": self.side,                              # "left" | "right" | "top" | "bottom"
            "x": round(self.x, 4),                          # rounded position x
            "y": round(self.y, 4),                          # rounded position y
            "width": self.width,                            # paddle width (constant)
            "height": self.height,                          # paddle height (constant)
            "score": self.score,                            # current score
            "connected": self.connected,                    # whether this slot has an active player
            "name": self.name,                              # display name
            "lastProcessedInputId": self.last_processed_input_id,  # for client-side reconciliation
            "votedToAbandon": self.votedToAbandon,          # abandon vote flag
        }


class PongGameState:
    """
    Single source of truth for the entire game.
    Holds ball, all four player slots, connection set, and game status.
    Responsible for physics update, collision detection, goal detection,
    and building the broadcast payload.
    """

    def __init__(self):
        self.status = "waiting"     # "waiting" | "countdown" | "playing" | "finished"
        self.tick = 0               # increments every physics update, used for reconciliation timing
        self.winner = None          # player id of the winner, None during play
        self.ball = Ball()          # single ball instance
        self.players = [            # four fixed slots, one per side — list literal
            Player(0, "left"),
            Player(1, "right"),
            Player(2, "top"),
            Player(3, "bottom"),
        ]
        self.spectators = []                        # list of spectator dicts
        self.connections: Set[WebSocket] = set()    # set of all active WebSocket connections

    def get_free_slot(self) -> Optional["Player"]:
        """
        Return the first player slot that is not connected, or None if all are taken.
        Uses a generator expression inside next() — iterates lazily and stops
        at the first match without scanning the whole list.
        """
        return next((p for p in self.players if not p.connected), None)  # generator expression

    def update_physics(self):
        """
        Advance the game by one tick.
        Order matters: move ball first, then check collisions (so we can correct
        the position immediately after penetration), then check goals, then move paddles.
        """
        self.tick += 1          # increment tick counter
        self.ball.update()      # move ball by vx/vy
        self.check_collisions() # detect and resolve paddle-ball collisions
        self.check_goal()       # detect if ball exited the field
        for player in self.players:  # move all paddles based on their current_direction
            player.move()

    def check_collisions(self):
        """
        AABB (Axis-Aligned Bounding Box) collision detection between ball and each paddle.
        For each connected player, checks if the ball's bounding circle overlaps
        the paddle rectangle. On hit: reverses the relevant velocity component,
        multiplies speed by 1.1 (acceleration), corrects ball position to prevent
        tunneling, and applies angular bounce based on impact point.
        """
        ball = self.ball

        for p in self.players:
            if not p.connected:     # skip disconnected slots
                continue

            # Compute paddle edges
            p_left   = p.x                  # left edge of paddle
            p_right  = p.x + p.width        # right edge of paddle
            p_top    = p.y                  # top edge of paddle
            p_bottom = p.y + p.height       # bottom edge of paddle

            # AABB check: ball circle overlaps paddle rectangle on both axes
            if (ball.x + ball.radius > p_left   and   # ball right side past paddle left edge
                ball.x - ball.radius < p_right  and   # ball left side before paddle right edge
                ball.y + ball.radius > p_top    and   # ball bottom past paddle top edge
                    ball.y - ball.radius < p_bottom): # ball top before paddle bottom edge

                # Resolve collision based on which wall the paddle is on
                if p.side == "left":
                    ball.vx = abs(ball.vx) * 1.1        # force vx positive (ball goes right) + accelerate
                    ball.x = p_right + ball.radius      # push ball outside paddle right edge (prevent tunneling)
                elif p.side == "right":
                    ball.vx = -abs(ball.vx) * 1.1       # force vx negative (ball goes left) + accelerate
                    ball.x = p_left - ball.radius       # push ball outside paddle left edge
                elif p.side == "top":
                    ball.vy = abs(ball.vy) * 1.1        # force vy positive (ball goes down) + accelerate
                    ball.y = p_bottom + ball.radius     # push ball outside paddle bottom edge
                elif p.side == "bottom":
                    ball.vy = -abs(ball.vy) * 1.1       # force vy negative (ball goes up) + accelerate
                    ball.y = p_top - ball.radius        # push ball outside paddle top edge

                self.apply_angular_bounce(p, ball)      # add angle variation based on impact point

    def apply_angular_bounce(self, player: "Player", ball: Ball):
        """
        Modify ball trajectory based on where it hits the paddle.
        Impact at the center - no angle change.
        Impact at the edges - steeper angle.
        Relative intersect is the normalized distance between impact point and paddle center.
        The multiplier (0.01) controls how extreme the angle effect is,for now purely a placeholder to be validated.
        """
        if player.side in ["left", "right"]:
            paddle_center = player.y + (player.height / 2)             # Y center of paddle
            relative_intersect = (ball.y - paddle_center) / player.height  # -0.5 to 0.5
            ball.vy += relative_intersect * 0.01                        # push vy based on impact point
        else:
            paddle_center = player.x + (player.width / 2)              # X center of paddle
            relative_intersect = (ball.x - paddle_center) / player.width   # -0.5 to 0.5
            ball.vx += relative_intersect * 0.01                        # push vx based on impact point

    def check_goal(self):
        """
        Detect if the ball has entirely exited the field (past any wall).
        Awards one point to all players except the loser.
        Resets the ball to center after a goal.
        Returns early if no goal has occurred (guard clause).
        """
        ball = self.ball
        margin = ball.radius    # use radius as tolerance so goal triggers when ball is fully outside

        # Guard clause: if ball is still inside the field, do nothing
        if not (ball.x < -margin or ball.x > 1 + margin or
                ball.y < -margin or ball.y > 1 + margin):
            return

        # Determine which side lost based on where the ball exited
        if ball.x < 0:
            loser_side = "left"
        elif ball.x > 1:
            loser_side = "right"
        elif ball.y < 0:
            loser_side = "top"
        else:
            loser_side = "bottom"

        # Award point to all players except the one who lost
        for p in self.players:
            if p.side != loser_side:    # everyone except the loser scores
                p.score += 1

        ball.reset()    # return ball to center with reversed direction

    def get_payload(self) -> dict:
        """
        Build the full gameState message dict ready for json.dumps().
        This is broadcast to all connected clients every tick.
        Structure matches the frontend's expected schema from GameState.js serialize().
        """
        return {
            "type": "gameState",    # message type identifier, read by frontend's message handler
            "payload": {
                "status": self.status,          # current game phase
                "tick": self.tick,              # tick counter for reconciliation timing
                "winner": self.winner,          # None during play, player id when finished
                "activePlayerCount": sum(1 for p in self.players if p.connected),  # generator expression inside sum()
                "aiEnabled": False,             # AI mode not yet implemented
                "aiPlayerSlot": None,           # AI slot not yet implemented
                "ball": self.ball.serialize(),  # ball position and velocity
                "players": [p.serialize() for p in self.players],  # list comprehension: serialize all 4 slots in one line
                "spectators": self.spectators,  # empty list, spectators not yet implemented
                "lobby": {"playersReady": []},  # lobby state, work in progress
            },
        }

    def get_lobby_state(self) -> dict:
        """
        Build the lobby state dict broadcast to all clients after every joinLobby.
        Contains the list of connected players, spectators, and canStart flag.
        canStart is True when at least 2 players are connected — matches the
        frontend's MIN_PLAYERS_TO_START logic in GameState.js canStartGame().
        """
        connected = [p for p in self.players if p.connected]   # list comprehension: only connected slots
        return {
            "players": [{"name": p.name} for p in connected],  # list comprehension: only name needed in lobby
            "spectators": self.spectators,                      # spectator list (empty until implemented)
            "canStart": len(connected) >= 2,                    # True when minimum players are present
        }


# =============================================================================
# SERVER CORE
# =============================================================================

game = PongGameState()  # single global game instance (one room)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    FastAPI lifespan context manager.
    Starts the world loop as a background task on server startup,
    cancels it cleanly on shutdown.
    """
    task = asyncio.create_task(world_loop())    # start game loop in background
    yield                                       # server runs here
    task.cancel()                               # cancel loop on shutdown


app = FastAPI(lifespan=lifespan)    # FastAPI instance with lifespan handler


async def world_loop():
    """
    Main game loop. Runs at 60fps.
    On each iteration:
      1. If game is playing, advance physics by one tick
      2. Serialize current game state to JSON string (once, reused for all clients)
      3. Broadcast to all connected clients concurrently using asyncio.gather
      4. Sleep for the remaining time to maintain 60fps cadence
    Serializing once and reusing the string avoids redundant work when
    there are multiple connected clients.
    """
    loop_time = 1 / 60  # target interval in seconds (~16.6ms)

    while True:
        start = time.time()                         # record tick start time

        if game.status == "playing":
            game.update_physics()                   # advance ball and paddles

        payload_json = json.dumps(game.get_payload())   # serialize once for all clients

        if game.connections:
            await asyncio.gather(                   # send to all clients concurrently
                *[ws.send_text(payload_json) for ws in list(game.connections)]  # positional unpacking + list comprehension unpacked into gather: send_text is an awaitable func,so if you call it without await it return a coroutine object. The list comprehension build a list of this coroutines,and the * unpacks them as arguments for gather,which executes them concurrently.
            )

        wait = loop_time - (time.time() - start)    # remaining time in this tick
        await asyncio.sleep(max(0, wait))           # sleep, clamped to 0 to avoid negative sleep


async def send_to(ws: WebSocket, type: str, payload: dict):
    """
    Send a single typed JSON message to one client.
    Wraps the message in the standard { type, payload } envelope.
    Used for one-off messages (playerAssigned, error, etc.) as opposed
    to the broadcast in world_loop which uses send_text directly.
    """
    await ws.send_text(json.dumps({"type": type, "payload": payload}))


async def broadcast(type: str, payload: dict):
    """
    Utility: send a single typed JSON message to ALL connected clients.
    Used for events that all clients need to receive simultaneously,
    such as lobbyUpdate — as opposed to send_to which targets one client.
    Reuses the same serialized string for all clients to avoid redundant work.
    """
    msg = json.dumps({"type": type, "payload": payload})    # serialize once for all recipients
    if game.connections:
        await asyncio.gather(                               # send concurrently to all clients
            *[ws.send_text(msg) for ws in list(game.connections)]  # list comprehension unpacked into gather
        )


@app.websocket("/ws")
async def websocket_endpoint(ws: WebSocket):
    """
    WebSocket connection handler. One coroutine instance runs per connected client.
    Accepts the connection, adds it to the global connections set,
    then loops waiting for messages.
    'player' starts as None and is assigned when joinLobby is received —
    initialized here so the except block can safely reference it even if
    the client disconnects before sending joinLobby.
    On disconnect or any exception, marks the player as disconnected,
    broadcasts the updated lobby state to remaining clients and
    removes the socket from the connections set.
    """
    await ws.accept()               # complete WebSocket handshake
    game.connections.add(ws)        # register connection for broadcasts
    player: Optional[Player] = None # will be assigned on joinLobby. Same of Union[Player, None] = None

    try:
        while True:
            data = await ws.receive_json()      # wait for next message, parsed as dict
            msg = ClientMessage(**data)         # validate envelope with Pydantic

            if msg.type == "joinLobby":
                parsed = JoinLobbyPayload(**msg.payload)    # validate joinLobby-specific payload
                player = game.get_free_slot()               # find first available slot
                if player:
                    player.connected = True                 # mark slot as occupied
                    player.name = parsed.playerName         # set display name
                    await send_to(ws, "playerAssigned", {   # confirm assignment to this client
                        "playerId": player.id,
                        "side": player.side,
                        "name": player.name,
                        "roomId": "main",
                        "gameStatus": game.status,
                    })
                    await broadcast("lobbyUpdate", game.get_lobby_state())  # notify ALL clients of updated lobby
                else:
                    await send_to(ws, "error", {"message": "Lobby full", "code": "LOBBY_FULL"})

            elif msg.type == "startGame":
                parsed = StartGamePayload(**msg.payload)    # validate startGame payload
                game.status = "playing"                     # transition game to playing state

            elif msg.type == "move":
                parsed = MovePayload(**msg.payload)         # validate move payload
                if player:
                    player.current_direction = parsed.direction         # saves current direction (None = stop),so the functio move read the direction and moves the paddle until None arrives: this guarantees smooth paddle movement
                    player.last_processed_input_id = parsed.inputId     # record for reconciliation echo

            elif msg.type == "voteAbandon":
                if player:
                    player.votedToAbandon = True            # flag this player's abandon vote

            elif msg.type == "restartGame":
                pass                                        # not yet implemented

    except (WebSocketDisconnect, Exception):
        if player:
            player.connected = False            # free up the slot
            player.current_direction = None     # stop any ongoing movement
        game.connections.discard(ws)            # discard (unlike remove, doesn't raise error if not present): first discard
        await broadcast("lobbyUpdate", game.get_lobby_state()) # then broadcast remaining clients that a player left