NAME = cub3D
CC	= cc
CFLAGS = -g -Wall -Wextra -Werror

INCLUDES = -I ./mlx -I ./include -I ./libft
LIBS = -L ./mlx -L ./libft ./mlx/libmlx.a ./libft/libft.a -lXext -lX11 -lm

SRC_DIR = src/
OBJ_DIR = obj/
INCLUDE_DIR = include/
LIBFT_DIR = libft/

SRC_FILES_BASE = main.c init/initialize.c init/init2.c \
			rendering/texture_draw.c rendering/dda.c \
			parsing/input.c parsing/parse_settings.c \
			parsing/parse_helpers.c parsing/parse_color.c \
parsing/parse_texture.c parsing/map.c \
			parsing/map_read.c parsing/map_utils.c \
			parsing/map_validate.c parsing/map_check.c \
			utils/escape.c utils/error.c

SRC_FILES = $(SRC_FILES_BASE) rendering/move.c

SRC_FILES_BONUS = $(SRC_FILES_BASE) rendering/move_bonus.c

OBJ_FILES = $(SRC_FILES:.c=.o)
OBJ_FILES_BONUS = $(SRC_FILES_BONUS:.c=.o)

SRC = $(addprefix $(SRC_DIR), $(SRC_FILES))
OBJ = $(addprefix $(OBJ_DIR), $(OBJ_FILES))
SRC_BONUS = $(addprefix $(SRC_DIR), $(SRC_FILES_BONUS))
OBJ_BONUS = $(addprefix $(OBJ_DIR), $(OBJ_FILES_BONUS))

MLX_LIB = ./mlx/libmlx.a
LIBFT = ./libft/libft.a

all: $(NAME)

$(NAME): $(LIBFT) $(OBJ) $(MLX_LIB)
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $(OBJ) $(LIBS)
	@echo "Executable $(NAME) created"

$(MLX_LIB):
	make -C ./mlx

$(LIBFT):
	make -C $(LIBFT_DIR)

$(OBJ_DIR)%.o: $(SRC_DIR)%.c
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -I$(INCLUDE_DIR) $(INCLUDES) -c $< -o $@

clean:
	make -C ./mlx clean
	make -C $(LIBFT_DIR) clean
	rm -rf $(OBJ_DIR) $(OBJ_FILES_BONUS)
	@echo "Object files removed"

fclean: clean
	make -C $(LIBFT_DIR) fclean
	rm -f $(NAME)
	@echo "Executable $(NAME) removed"

bonus: $(LIBFT) $(OBJ_BONUS) $(MLX_LIB)
	$(CC) $(CFLAGS) $(INCLUDES) -o $(NAME) $(OBJ_BONUS) $(LIBS)
	@echo "Bonus executable $(NAME) created"

re: fclean all

git:
	make fclean
	git add .
	git commit -m "update"
	git push

.PHONY: all clean re fclean git bonus
