# Generated by Django 6.0.4 on 2026-05-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='use',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
