# Generated by Django 5.2.14 on 2026-05-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_badge_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_warning',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
