# Generated by Django 5.2.14 on 2026-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_badge_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intra_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
