# Generated by Django 5.2.14 on 2026-05-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_warning_user_muted_until'),
        ('accounts', '0004_user_profile_picture'),
    ]

    operations = [
    ]
