Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "dridolfoS" do |server|
    server.vm.hostname = "dridolfoS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.name = "dridolfoS"
      v.memory = 2048
      v.cpus = 2
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "dridolfoSW" do |worker|
    worker.vm.hostname = "dridolfoSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |v|
      v.name = "dridolfoSW"
      v.memory = 512
      v.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
