services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/conf.d
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
  
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name : wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WP_DB_HOST: ${MYSQL_HOST}
      WP_DB_USER: ${MYSQL_USER}
      WP_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_DB_NAME: ${MYSQL_DATABASE}
      DOMAIN_NAME: ${DOMAIN_NAME}

      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}

      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      MYSQL_HOST: ${MYSQL_HOST}
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      device: /home/ecaruso/data/mariadb
      o: bind
      type: none
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      device: /home/ecaruso/data/wordpress
      o: bind
      type: none

networks:
  inception:
    driver: bridge
