events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Redirect HTTP a HTTPS
    server {
        listen 80;
        listen [::]:80;
        server_name localhost;

        return 301 https://$host:8443$request_uri;
    }

    # Server HTTPS con reverse proxy per Django e Next.js
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name localhost;

        # Certificati SSL
        ssl_certificate     /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        # Configurazioni di sicurezza SSL standard
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        # Proxy headers
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # --- REVERSE PROXY PER IL BACKEND ---
        location /api/ {
            proxy_pass http://backend:8000;
        }

        location /admin/ {
            proxy_pass http://backend:8000;
        }

		location /oauth/ {
			proxy_pass http://backend:8000;
		}

		# Endpoint di autenticazione
		location /auth/ {
			proxy_pass http://backend:8000;
		}

		# Static files per django admin
		location /static/ {
			alias /app/staticfiles/;
		}

		# Static files per profile picture
		location /media/profile_pictures/ {
			alias /app/media/profile_pictures/;
		}

		# --- GESTIONE WEBSOCKET ---
		location /ws/ {
		    proxy_pass http://backend:8000;

		    # WebSocket support
		    proxy_http_version 1.1;
		    proxy_set_header Upgrade $http_upgrade;
		    proxy_set_header Connection "upgrade";

		    # Proxy headers
		    proxy_set_header Host $host;
		    proxy_set_header X-Real-IP $remote_addr;
		    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		    proxy_set_header X-Forwarded-Proto $scheme;

		    # Timeout di connessione
		    proxy_read_timeout 86400s;
		    proxy_send_timeout 86400s;
		}

        # --- REVERSE PROXY PER IL FRONTEND ---
        location / {
            proxy_pass http://frontend:3000;

			# WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
