# Generated by Django 5.2.14 on 2026-05-05 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalMultiplayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users', models.JSONField(default=list)),
                ('code', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_ids', models.JSONField(default=list)),
                ('question_number', models.IntegerField(default=0)),
                ('status', models.CharField(default='waiting', max_length=255, null=True)),
                ('current_answers', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Multiplayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users', models.JSONField(default=list)),
                ('code', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_ids', models.JSONField(default=list)),
                ('question_number', models.IntegerField(default=0)),
                ('status', models.CharField(default='waiting', max_length=255, null=True)),
                ('current_answers', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000, null=True)),
                ('a', models.CharField(max_length=1000, null=True)),
                ('b', models.CharField(max_length=1000, null=True)),
                ('c', models.CharField(max_length=1000, null=True)),
                ('d', models.CharField(max_length=1000, null=True)),
                ('answer', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OldMatches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('mode', models.CharField(max_length=100, null=True)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='SinglePlayerMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('question_ids', models.JSONField(default=list)),
                ('question_number', models.IntegerField(default=1)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('fifty_fifty', models.BooleanField(default=True)),
                ('change_question', models.BooleanField(default=True)),
                ('double_chance', models.BooleanField(default=True)),
                ('refill_time', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
