# Generated by Django 5.2.15 on 2026-06-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oldmatches",
            name="ranking",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
