version: '3.8'

services:

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    restart: unless-stopped

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception_network:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt