
NAME = thejobofyourdreams
SRC = src/account.cpp src/tests.cpp
OBJ = $(SRC:.cpp=.o)
CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98
RM = rm -rf
INC = -Iinc/

%.o: %.cpp
	$(CC) $(CFLAGS) $(INC) -O3 -c $< -o $@
		
$(NAME): $(OBJ)
	@$(CC) $(OBJ) -o $(NAME)
		
all: $(NAME)	

clean:
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean .cpp.o

